services:
  lobby:
    image: ghcr.io/erik1000/minecraft-server-docker:base-latest
    env_file: .env
    environment:
      - CFG_SERVER_NAME=Lobby
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - "./server:/data"
  plot:
    image: ghcr.io/erik1000/minecraft-server-docker:plot-latest
    env_file: .env
    environment:
      - CFG_SERVER_NAME=Plot
    volumes:
      - "./plot:/data"
  proxy:
    image: ghcr.io/erik1000/minecraft-server-docker:velocity-latest
    env_file: .env
    environment:
      - CFG_SERVER_NAME=Velocity
    ports:
      - "0.0.0.0:25577:25577"
    volumes:
      - "${PWD}/velocity.toml:/config/velocity.toml:ro"
      - "./proxy:/server"