name: build and publish docker images
on:
    schedule:
         - cron: "0 3 */2 * *"
    workflow_dispatch:
        inputs:
            version:
                description: "Minecraft server version"
                required: false
                type: string
                default: "latest"
            velocity_version:
                description: "Velocity proxy version"
                required: false
                type: string
                default: "latest"
env:
    REGISTRY: "ghcr.io"
    IMAGE_NAME: "${{ github.repository }}"
    VERSION: "${{ inputs.version }} || '1.21.4'"
    VELOCITY_VERSION: "${{ inputs.velocity_version }} || 'latest'"
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
jobs:
    base:
        environment: build
        runs-on: ubuntu-latest
        steps:
            - name: version
              run: echo "using version ${{ env.VERSION }}"
            - uses: actions/checkout@v4
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: setup metadata
              uses: docker/metadata-action@v5
              id: metadata
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} "
                  tags: base-latest

            - name: log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: "."
                  push: true
                  file: Dockerfile.base
                  tags: "${{ steps.metadata.outputs.tags }}"
                  no-cache: true
                  build-args: version=${{ env.VERSION }}
    plot:
        environment: build
        needs: base
        runs-on: ubuntu-latest
        steps:
            - name: version
              run: echo "using version ${{ env.VERSION }}"
            - uses: actions/checkout@v4
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: setup metadata
              uses: docker/metadata-action@v5
              id: metadata
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} "
                  tags: plot-latest

            - name: log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: "."
                  push: true
                  file: Dockerfile.plot
                  tags: "${{ steps.metadata.outputs.tags }}"
                  no-cache: true
                  build-args: version=${{ env.VERSION }}
    grastaxi:
        environment: build
        needs: base
        runs-on: ubuntu-latest
        steps:
            - name: version
              run: echo "using version ${{ env.VERSION }}"
            - uses: actions/checkout@v4
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: setup metadata
              uses: docker/metadata-action@v5
              id: metadata
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} "
                  tags: grastaxi-latest

            - name: log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: "."
                  push: true
                  file: Dockerfile.grastaxi
                  tags: "${{ steps.metadata.outputs.tags }}"
                  no-cache: true
                  build-args: version=${{ env.VERSION }}
    velocity:
        environment: build
        runs-on: ubuntu-latest
        steps:
            - name: version
              run: echo "using version ${{ env.VELOCITY_VERSION }}"
            - uses: actions/checkout@v4
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: setup metadata
              uses: docker/metadata-action@v5
              id: metadata
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} "
                  tags: velocity-latest

            - name: log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: "."
                  push: true
                  file: Dockerfile.velocity
                  tags: "${{ steps.metadata.outputs.tags }}"
                  no-cache: true
                  build-args: version=${{ env.VERSION }}
