name: build and publish docker images
on:
    workflow_dispatch:
        inputs:
            version:
                description: "Minecraft server version"
                required: true
                type: string
env:
    REGISTRY: "ghcr.io"
    IMAGE_NAME: "${{ github.repository }}"
    VERSION: "${{ inputs.version }}"
jobs:
    build:
        environment: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - dockerfile: Dockerfile.base
                      image: base
                    - dockerfile: Dockerfile.plot
                      image: plot
                    - dockerfile: Dockerfile.velocity
                      image: velocity
        steps:
            - name: version
              run: echo "using version ${{ env.VERSION }}"
            - uses: actions/checkout@v4
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: setup metadata
              uses: docker/metadata-action@v5
              id: metadata
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} "
                  tags: "${{ matrix.image }}-latest"

            - name: log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: "."
                  push: true
                  file: ${{ matrix.dockerfile }}
                  tags: "${{ steps.metadata.outputs.tags }}"
                  no-cache: true
                  build-args: version=${{ inputs.version }}
